In file included from ../src/bufferutil.cc:15:
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:213:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:209:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(fun(v8::String::New(errmsg)));                        \
      ~~~~^
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:213:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:209:42: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(fun(v8::String::New(errmsg)));                        \
                             ~~~~~~~~~~~~^
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:218:9: error: no type named 'ThrowException' in namespace 'v8'
    v8::ThrowException(error);
    ~~~~^
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:222:65: error: no member named 'New' in 'v8::String'
    v8::Local<v8::Value> err = v8::Exception::Error(v8::String::New(msg));
                                                    ~~~~~~~~~~~~^
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:223:50: error: expected '(' for function-style cast or type construction
    v8::Local<v8::Object> obj = err.As<v8::Object>();
                                       ~~~~~~~~~~^
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:223:52: error: expected expression
    v8::Local<v8::Object> obj = err.As<v8::Object>();
                                                   ^
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:224:65: error: too few arguments to function call, expected 2, have 1
    obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
                                      ~~~~~~~~~~~~~~            ^
/Users/jason/.node-gyp/0.12.2/deps/v8/include/v8.h:2012:3: note: 'New' declared here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
In file included from ../src/bufferutil.cc:15:
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:224:26: error: no member named 'New' in 'v8::String'
    obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
             ~~~~~~~~~~~~^
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:229:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:209:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(fun(v8::String::New(errmsg)));                        \
      ~~~~^
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:229:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:209:42: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(fun(v8::String::New(errmsg)));                        \
                             ~~~~~~~~~~~~^
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:233:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:209:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(fun(v8::String::New(errmsg)));                        \
      ~~~~^
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:233:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:209:42: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(fun(v8::String::New(errmsg)));                        \
                             ~~~~~~~~~~~~^
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:450:49: error: too few arguments to function call, single argument 'isolate' was not specified
    v8::Local<v8::Object> obj = v8::Object::New();
                                ~~~~~~~~~~~~~~~ ^
/Users/jason/.node-gyp/0.12.2/deps/v8/include/v8.h:2388:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
In file included from ../src/bufferutil.cc:15:
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:451:14: error: no member named 'NewSymbol' in 'v8::String'
    obj->Set(NanSymbol("callback"), fn);
             ^~~~~~~~~~~~~~~~~~~~~
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:103:38: note: expanded from macro 'NanSymbol'
#define NanSymbol(value) v8::String::NewSymbol(value)
                         ~~~~~~~~~~~~^
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:457:12: error: no member named 'Dispose' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    handle.Dispose();
    ~~~~~~ ^
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:458:12: error: no member named 'Clear' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    handle.Clear();
    ~~~~~~ ^
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:463:10: error: use 'template' keyword to treat 'As' as a dependent template name
        .As<v8::Function>();
         ^
         template 
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:462:46: error: no member named 'NewSymbol' in 'v8::String'
    return NanPersistentToLocal(handle)->Get(NanSymbol("callback"))
                                             ^~~~~~~~~~~~~~~~~~~~~
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:103:38: note: expanded from macro 'NanSymbol'
#define NanSymbol(value) v8::String::NewSymbol(value)
                         ~~~~~~~~~~~~^
/Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/nan/nan.h:475:35: error: use 'template' keyword to treat 'As' as a dependent template name
       Get(NanSymbol("callback")).As<v8::Function>();
                                  ^
                                  template 
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jason/mean_chapter8/node_modules/socket.io/node_modules/engine.io/node_modules/ws
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
